import Head from 'next/head'
import ComoFunciona from '../components/Home/ComoFunciona'
import Hero from '../components/Home/Hero'
import PortalCreditos from '../components/Home/PortalCreditos'
import Vantagens from '../components/Home/Vantagens'
import Navbar from '../components/Navbar'

export default function Home() {
  let lang = 'pt-br'
  return (
    <div>
      <Head>
        <title>InterJud | Plataforma de negociação de crédito judicial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="shortcut icon" type="image-x/png" href="https://www.interjud.com.br/icon.png" />
        <meta charSet="UTF-8" />
      </Head>
      <Navbar />
      <Hero />
      <PortalCreditos />
      <ComoFunciona />
      <Vantagens />
    </div>
  )
}
